on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '2,12,22,32,42,52 * * * *' # every 10 minutes for the initial test
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data from the API endpoint
      run: |-
        curl -s "https://hub.docker.com/v2/repositories/dustynv/?page=1&page_size=1000" | jq '.results'> dockerhub.json
    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
